---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  "/api/v1/metrics":
    post:
      tags:
        - metrics-controller
      operationId: postMetrics
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/MetricDto"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
components:
  schemas:
    MetricDto:
      type: object
      properties:
        methodName:
          type: string
        avgRuntime:
          type: number
          format: double
        exceptionsOccurred:
          type: integer
          format: int64
        longestRuntime:
          type: integer
          format: int64
